### ISSUE TITLE
remove fall stagger for shorter falls

### ISSUE THREAD

**Issue by Bobbsify** [Bobbsify/Splitting#13]
La caduta da OGNI altezza causa lo stagger ed un rallentamento, rimuoverla per cadute inferiori ad una certa altezza velocizzerebbe molto il gameplay

**Comment by Ventricolodx** [comment]
Ora all'interno del Jump si può decidere il timerFall, ovvero il tempo minimo necessario per triggherare lo screen shake dopo l'atterraggio di Ant. Inoltre ora l'animazione di atterraggio non ha più l'exit time e ciò fa si che dopo l'atterraggio il giocatore possa subito tornare a muoversi.
