### ISSUE TITLE
Fix Input Lag

### ISSUE THREAD

**Issue by Bobbsify** [Bobbsify/Splitting#14]
C'è un serio input lag in certi momenti del gioco che lo rallenta molto, si può sistemare, a mio parere, tagliando la durata di certe animazioni o migliorando i calcoli nei sistemi di Input, bisognerebbe discuterne

**Comment by Bobbsify** [comment]
Secondo me l'idea di Input Lag che è uscita dal mio playtest è data dalla lentezza di certe animazioni e/o transizioni

Per esempio per il grab di Tyr la velocità potrebbe essere raddoppiata (Quella dell'animazione) e la durata della transizione resa al minimo (Non so se è già così)

**Comment by Ventricolodx** [comment]
fatto
