### ISSUE TITLE
make Ant grab boxes from top

### ISSUE THREAD

**Issue by Bobbsify** [Bobbsify/Splitting#19]
In questo momento se una cassa colpisce la testa di ant da qualsiasi direzione ant la grabberà, bisognerebbe fare che solo le casse con Y > di quella di ant e X in un certo range sopra di lui vengano considerate come "Prendibili"

**Comment by Ventricolodx** [comment]
Ora le casse vengono carryate da ant solo quando le loro coordinate rientrano in un certo range.
